### ISSUE TITLE
Update Individual.__hash__ to use chromosomes

### ISSUE THREAD

**Issue by inspectorG4dget** [inspectorG4dget/Genetic-Framework#8]
Currently, `Individual.__hash__` uses `Individual.__class__.ID` as a uniqueness guarantor. This was originally dreamt up as a hack to ensure that `__hash__` works correctly. This has the unfortunate consequence that pickled Individuals cannot be injected into the population as their IDs may be shared by others. 

Therefore, a new `Individual.__hash__` is required. This must `tuple`-ify the chromosomes and hash the results. This must deprecate and delete `Individual.__class__.ID`

**Comment by ghost** [comment]
This issue seems to have been fixed already in code. Isn't it?

**Comment by inspectorG4dget** [comment]
You're right. This issue is no longer relevant
